SELECT
    LGL_IND,
    MAINFRM_ERR_IND,
    MAINFRM_ERR_TXT,
    MAINFRM_UPLD_DT,
    MAINFRM_UPLD_IND,
    MAINFRM_WRN_IND,
    MAINFRM_WRN_TXT,
    SUB_TASK_CD,
    SUB_TASK_DESC,
    SUB_TASK_SHRTNM,
    SYS_USER_ID,
    TASK_CD,
    TASK_SUBTASK_ID,
    TIMESTAMP
FROM ADMIN.TTASK_SUBTASK
WHERE TASK_CD = 'A05'